### ISSUE TITLE
1.8 版在 Firefox68 下视频画面抖动

### ISSUE THREAD

**Issue by biubiuboom** [tiansh/ass-danmaku#10]
通过逐一禁用附加组件排查到的，哔哩哔哩视频画面播放时有随机的抖动，特别是画面切换频繁的视频更明显。

**Comment by tiansh** [comment]
这插件没动任何界面上的东西，所以我觉得这事不是这插件能弄出来的。

**Comment by biubiuboom** [comment]
好的，我继续核查其他原因。感谢大佬的插件，真的很好用~
