### ISSUE TITLE
救命: 火狐77地址栏下载 ass 文件选项失效了

### ISSUE THREAD

**Issue by HayashiKaori** [tiansh/ass-danmaku#12]
估计因为火狐又限制了权限？
重装PC、浏览器、插件也无效。

**Comment by MC-dusk** [comment]
[AMO](https://addons.mozilla.org/en-US/firefox/addon/ass-danmaku/) can't use.

>在支持的网站观看视频，下载按钮将会出现在地址栏右侧。

Nothing appeared when I visit bili, ac.

**Comment by tiansh** [comment]
应该是网站换了数据格式，得过几天。

**Comment by tiansh** [comment]
bilibili 这个更麻烦。他们用的这个库里面一堆 eval，在扩展里面跑不起来……
