### ISSUE TITLE
新增 ひまわり動画 支援

### ISSUE THREAD

**Issue by jloqfjgk** [tiansh/ass-danmaku#14]
希望可以新增支援這個網站：
`http://himado.in`

XML 格式似乎與 Niconico 類似。

在網頁源代碼中尋找 `commentdlform`，可以得知某影片的 XML 下載路徑參數，例如 `http://himado.in/486284` ：
```
<input type="hidden" name="id" value="486284">
<input type="hidden" name="group_id" value="547298">
<input type="hidden" name="mode" value="comment">
<input type="hidden" name="key" value="162">
<input type="hidden" name="format" value="nico">
```
`id` 可以從影片 URL 得知，但 `group_id` 和 `key` 需要從該影片的網頁源代碼中尋找。
另外也需要 `limit` 參數，可以選擇下載多少數量的彈幕，最多 20000 。

**Comment by tiansh** [comment]
這裡下載的彈幕是根據網站本身載入的彈幕生成的。不會主動去發起 HTTP 要求。所以 `limit` 引數的配置可能對我沒什麼用。總之我有空看看，不過大概先處理完前面那個 bilibili 下載不完整的問題之後……

**Comment by tiansh** [comment]
1.12 已更新

**Comment by jloqfjgk** [comment]
好快！

測試後暫未發現問題，彈幕下載完整。

真的非常感謝！
