### ISSUE TITLE
在线转换网址什么时候可以修复一下，选择xml文件后没有反应

### ISSUE THREAD

**Issue by heavytable** [tiansh/ass-danmaku#19]
https://tiansh.github.io/ass-danmaku-online/，这个网页
还有一个简约版网页但是无法调整弹幕速度大小等，所以只想用这个

**Comment by tiansh** [comment]
能不能给个 xml 附件，我看看……

**Comment by heavytable** [comment]
[弹幕示例.zip](https://github.com/tiansh/ass-danmaku/files/8965901/default.zip)
这些弹幕是我自己用python爬的，来自爱奇艺，留下了时间和颜色等等简单信息，danmu2ass那个软件是转不了的，但是danmakuFactory是可以转的，也就是说我的xml格式没问题，但是会有重叠那种影响，你那个网页也可以转（ http://tiansh.github.io/us-danmaku/bilibili/   ），只不过调整不了速度，我就找到你主页看到还有这么一个版本哈哈哈

**Comment by tiansh** [comment]
看了一下，你这个不是 bilibili 的格式……所以还要再处理……
爱奇艺有哪个可以免费观看的视频有用到这个格式的弹幕文件吗，我可能需要看一下再看怎么处理……

**Comment by heavytable** [comment]
http://tiansh.github.io/us-danmaku/bilibili/  就我说的这个页面是可以转换的，也可以正常显示，只不过时间上有点问题，为什么呢，所以我猜想只要这个网页开放持续时间等等修改属性的可选项就可以吧

**Comment by tiansh** [comment]
bilibili 下载的弹幕现在这个网页应该可以正常转换了（应该），但是你这个应该还是不行。两边处理逻辑不太一样，具体的我没仔细看。

**Comment by heavytable** [comment]
粉色这个网页是一直可以转换的，我现在想问的就是，为什么不能把粉色这个网页转换的属性暴露出来，因为转出来的格式观看体验不太好，因为既然你说逻辑不一样，那为什么我用粉色这个网站是可以转化并且使用的呢，黑白网页这个既然处理不了那就是逻辑不一样，那能不能改下粉色网站的接口（如果用到了接口的话，那应该有相关属性设置吧）

**Comment by tiansh** [comment]
之前那个的话，你在代码里面找一找应该能找到哦一段设置。改了之后或许可以满足你说的需求。
这个我确认了一下，脚本是通过 `<chatid>` 这个标签来判断是 bilibili 的弹幕格式的。你的文件里面没有这个标签，所以他没识别。你可以给他加一个假的 `<chatid></chatid>` 应该能骗过去。

**Comment by heavytable** [comment]
我按照你的意思还有B站弹幕构成，修改了一下爬虫规则，写进去了一些伪装内容，现在用可调参数那个网站已经成功弄出来非常完美的字幕了哈哈哈哈谢谢！！
