### ISSUE TITLE
Addon stopped working after lastest update of the site

### ISSUE THREAD

**Issue by legionfrontier** [tiansh/ass-danmaku#2]
Greetings, I will like to thank you for this nice addon, I used it a few times and It worked great, however NicoVideo changed they back end and this addon seems to no longer downloading the danmaku again, could you try take a look at it again? I was in the middle of archiving some stuff in case they decide to go down again

**Comment by tiansh** [comment]
Could you please describe some more details about your problem such as which video (link), and your configuration? I just could not reproduce your problem. I had just tried to watch some video on the home page [sm33713849](http://www.nicovideo.jp/watch/sm33713849) while language configured to Japanese, locale configured to Japan without login. And it successfully downloaded an ASS file with 18 comments in it.

**Comment by legionfrontier** [comment]
I tried with many other videos, including yours and the "Download Damnaku" appears unable/grey out, tried in also an older firefox version and the current one, I also have the same Japan/Japanese settings, Im logged in

**Comment by tiansh** [comment]
Thanks to your report. @winnie93123 had submitted a fix for this issue, and version 1.6 had been published. Please try to upgrade to that version to verify if everything just works fine.

**Comment by legionfrontier** [comment]
Can confirm that is working again, thanks to @winnie93123 for the fix.
Also I will like to ask if possible, how can you grab the .json file with the danmaku manually if you can?
I see that is from nmsg.nicovideo.jp/api.json/ , so what exactly I will need to add to that url to grab for example, this http://www.nicovideo.jp/watch/sm17507922 or any other video? thank you

**Comment by tiansh** [comment]
You may download the JSON file directly if you want keep the comments in its original format. The easiest way to do so is:

* Open developer panel
* Switch to Network tab
* Navigate to open some video
* You will see the request in the list
* Right click on it and open its response in new window
* Save it to your local disk

**Comment by tiansh** [comment]
It is a POST request, so maybe some parameters but I dont know. Maybe some other related tools could be useful then.

**Comment by legionfrontier** [comment]
Ok, is thanks for the help @tiansh @winnie93123
