### ISSUE TITLE
新增巴哈姆特動畫瘋支援

### ISSUE THREAD

**Issue by enstk99** [tiansh/ass-danmaku#5]
希望可以新增支援這個網站：
https://ani.gamer.com.tw/

有興趣協助

**Comment by tiansh** [comment]
我可能要过两天才有空看，你如果想自己搞可以仿照 niconico.js 或者 bilibili.js 自己搞然后 pr 过来，或者过两天我写个基础的出来你再看着调整和测试一下……

**Comment by tiansh** [comment]
可以簽出到 [bahamut 分支](https://github.com/tiansh/ass-danmaku/tree/bahamut)，或在這個網頁上下載 zip 檔案。解壓縮之後使用 Firefox 選擇「對附加元件除錯」之後「載入暫用附加元件…」，選擇 manifest.json 檔案。之後打開對應的網站就可以下載彈幕了。

我這邊看不到這個網站的實際展示效果，所以我不能確定我寫的轉換規則是否正確，請根據網站的效果檢查彈幕的顏色、位置、時間等設定是否正確。

如果有問題可以在這回復，也可以 PR 過來。

**Comment by enstk99** [comment]
https://send.firefox.com/download/db31d740af11080f/#qvldTcKGNYtnfw7g7T6nYQ
https://send.firefox.com/download/fcc05d310793bec7/#Z5hB4lLQSIHaA-5OKumJaA
看起來彈幕位置會上下顛倒，時間軸沒有問題。
用PowerPoint錄製的，影片有點差。（左邊有用彈幕過濾，所以稍微有點差別）

**Comment by tiansh** [comment]
彈幕發送一共有幾種字型大小可選？他們的字型大小（單位：像素）應該是多少？我這是直接套用了 niconico 那邊的處理，這個也麻煩確認一下。

**Comment by enstk99** [comment]
小中大
16,24,28px

**Comment by tiansh** [comment]
我又更新了這個分支，可以再試一試，看看現在是否一切正常。

**Comment by enstk99** [comment]
少部分滾動彈幕位置跟線上看位置不一樣，但不影響。
固定彈幕的位置，確認正確。

基本上正常。

**Comment by tiansh** [comment]
1.8 已可從 AMO 安裝。
