### ISSUE TITLE
;、*等特殊符号未去除，之后内容的解析会失败

### ISSUE THREAD

**Issue by B-sirius** [tiansh/ass-danmaku#6]
发现解析后的弹幕少了很多，只有前n分钟的部分，仔细看了下发现出现;、*等特殊字符后面的弹幕就没了。大概是不符合xml的规范之类吧......解析前还是直接删除掉这些不对头的字段吧

**Comment by tiansh** [comment]
有没有测试的例子，直接给我 xml 也可以，给我网址也可以

**Comment by B-sirius** [comment]
[45104-2017-10-14-20-5-33.xml.zip](https://github.com/tiansh/ass-danmaku/files/3107138/45104-2017-10-14-20-5-33.xml.zip)
这是b站17年10月某直播的弹幕，解析成.ass后到23分钟左右就没有了，从文件体积上也能很明显的看出来

**Comment by tiansh** [comment]
我用那个在线转换的工具试了一下你给的文件，是因为 xml 含有非法的 & 字符所以出错了。
和;或者*倒是没关系。
我也不知道这个怎么处理。

**Comment by B-sirius** [comment]
> 我用那个在线转换的工具试了一下你给的文件，是因为 xml 含有非法的 & 字符所以出错了。
> 和;或者*倒是没关系。
> 我也不知道这个怎么处理。

明白了，不过不可以在处理前先去除这些含非法字符的弹幕么，个人觉得少几条弹幕其实没有什么实质影响。总之我先关掉这个issue，谢谢回复。
